language: scala

jdk:
  - openjdk11

scala:
  - 2.13.0

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork


script: travis_retry sbt ++$TRAVIS_SCALA_VERSION test

jobs:
  include:
    - name: compile
      script: sbt clean coverage test coverageAggregate codacyCoverage
    - name: formatting
      script: sbt scalafmtCheckAll
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release